### ISSUE TITLE
LSD spec: id and name should be mandatory in renew and return

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-specs#14]
So that rogue renew/return is more difficult via the server api.
A renew that displays a web page does not enforce this rule.

**Comment by HadrienGardeur** [comment]
How would that work?

This would enforce registration of a given id/name before? This seems very error prone, and renew/return shouldn't be tied to registration.

**Comment by llemeurfr** [comment]
Why error prone? the device know its id and name and can send it with renew/return as it does with register.
Why shouldn't renew/return be tied to registration? there is a requirement for a device to register (once) for a given license. The server records the event; then, and then only, a loan may be renewed/returned from the device. The server can easily check that the device has been registered before allowing a renew/return.

**Comment by jpbougie** [comment]
It doesn't make sense to me that an ILS be required to register as a device on the license in order to allow a user to conduct the interactions from the website. We still want to show the device/agent in order to help the user remember where he took an action (on the app or on his library platform), which is why the name and id are still relevant, but I don't see how they fit with the registration flow. 

In addition, it raises some questions about when exactly the device is to be registered. You could technically return a book from a device on which you've never accessed the content. Should you still need to register the device in that case?

**Comment by llemeurfr** [comment]
I have been thinking about your arguments, they make sens and you're the creators of the spec, therefore I'll close this issue.
